#include <iostream>
#include <d3d11.h>
#include <wrl.h>
#include "Error.h"
#include <DirectXMath.h>
#include "VertexBuffer.h"
#include "IndexBuffer.h"
#include "CBuffer.h"
#include "Camera3D.h"
#include "Shaders.h"
#include "InputLayout.h"
#include "imgui\imgui.h"
#include <DirectXTex.h>
#include "Timer.h"	
#include "Model.h"
#include "UI.h"
#include "Timer.h"
#include "PointLight.h"